<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Diagnostics.Tracing.TraceEvent"><HintPath>../dotnet-trace-tool/Microsoft.Diagnostics.Tracing.TraceEvent.dll</HintPath><Private>true</Private></Reference>
    <Reference Include="Microsoft.Diagnostics.FastSerialization"><HintPath>../dotnet-trace-tool/Microsoft.Diagnostics.FastSerialization.dll</HintPath><Private>true</Private></Reference>
  <Reference Include="Microsoft.Diagnostics.NETCore.Client"><HintPath>../dotnet-trace-tool/Microsoft.Diagnostics.NETCore.Client.dll</HintPath><Private>true</Private></Reference>
  </ItemGroup>
</Project>
