import hashlib,json,pathlib,re,math
w=pathlib.Path('/tmp/deepseek41-reference/final-raw');p='tp8-context65536-ubatch1024-cpumoe0-sparse1-compact1-slots4-chunk1024-b26c-tools';cur=pathlib.Path('/Users/zhongkaifu/work/TensorSharp/docs/validation/deepseek41/full-checkpoint')
def src(path):return {'path':str(path),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()}
manifest=json.load(open(w/(p+'-placement-runs.json')));data=(w/(p+'-server.log')).read_bytes();runs=[]
for r in manifest['runs']:
 a=r['native_accounting'];blob=data[a['byte_start']:a['byte_end']];forwards=[(int(n),float(t)) for n,t in re.findall(rb'\[dsv4\] forward (\d+) tokens in ([\d.]+)s',blob)]
 computed={'prefill_calls':sum(n>1 for n,t in forwards),'prefill_tokens':sum(n for n,t in forwards if n>1),'prefill_forward_seconds':sum(t for n,t in forwards if n>1),'decode_calls':sum(n==1 for n,t in forwards),'decode_forward_seconds':sum(t for n,t in forwards if n==1)}
 raw=w/(p+'-'+r['label']+'.json');d=json.load(open(raw));published=json.load(open(cur/raw.name));chats=[(int(n),int(pr),int(reused),reason.decode()) for n,pr,reused,reason in re.findall(rb'chat.complete tokens=(\d+) promptTokens=(\d+) kvReused=(\d+).*?finishReason=(\S+)',blob)]
 prompts=sum(pr for n,pr,reuse,reason in chats);reused=sum(reuse for n,pr,reuse,reason in chats);tokens=sum(n for n,pr,reuse,reason in chats);eos=sum(reason=='eos' for n,pr,reuse,reason in chats)
 problems=[line.decode(errors='replace') for line in blob.splitlines() if re.search(rb'error|failed|assert|preempt|exception',line,re.I)]
 checks={'source_report_hash_matches_curated':src(raw)['sha256']==published['source_report_sha256'],'range_sha256_matches':hashlib.sha256(blob).hexdigest()==a['range_sha256'],'native_counters_match':all(math.isclose(a[k],v,rel_tol=1e-12,abs_tol=1e-9) for k,v in computed.items()),'child_exit_zero':r['exit_code']==0,'run_complete':d.get('run_complete') is True,'planned_count_matches':len(d['cases'])==d['execution_plan']['expected_cases'],'all_cases_passed':all(c['status']=='ok' for c in d['cases']),'warmup_passed':d.get('warmup',{}).get('status')=='ok','no_error_or_preemption_lines':not problems,'prefill_reconciles':computed['prefill_tokens']==prompts-reused,'decode_reconciles':computed['decode_calls']==tokens+eos}
 runs.append({'label':r['label'],'source':src(raw),'checks':checks,'all_audit_checks_passed':all(checks.values()),'case_count':len(d['cases']),'computed_native':computed,'chat_complete_count':len(chats),'chat_prompt_tokens_including_warmup':prompts,'reused_prompt_tokens':reused,'chat_generated_tokens_including_warmup':tokens,'eos_forward_count':eos,'range_sha256':a['range_sha256'],'error_lines':problems})
result={'profile':p,'scope':'Independent local verification of completed FIRST TP baseline. No isolated TP-vs-layer causal performance claim.','audit_source':src(pathlib.Path(__file__)),'placement_runs_source':src(w/(p+'-placement-runs.json')),'server_log_source':src(w/(p+'-server.log')),'runner_updated_source':src(pathlib.Path('/tmp/deepseek41-reference/run-final-suite.py')),'runner_previous_behavior':'Previous wrapper recorded child codes but did not propagate failure or mark phase completeness. Childreports/nativebyte-ranges audited directly here. New wrapper fixes future phase reporting.','runs':runs}
pathlib.Path('/tmp/deepseek41-reference/placement-first-tp-audit.json').write_text(json.dumps(result,indent=2)+'\n')
print([(r['label'],r['all_audit_checks_passed']) for r in runs])
