"""Read-only CPU-MoE4 placement audit; preserves failed cases."""
import argparse,copy,hashlib,json,math,pathlib,re,statistics
ap=argparse.ArgumentParser();ap.add_argument('--output',type=pathlib.Path,default=pathlib.Path('/tmp/deepseek41-reference/cpu4-placement-audit.json'));args=ap.parse_args()
w=pathlib.Path('/tmp/deepseek41-reference/final-raw');p='layer8-context65536-ubatch1024-cpumoe4-cputhreads48-sparse1-compact1-chunk1024-3b88'
def source(path): return {'path':str(path),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()}
def load(label):return json.loads((w/(p+'-'+label+'.json')).read_text())
manifest=load('placement-runs');serial_manifest=load('serial-tools-runs');launch=load('launch');log=(w/(p+'-server.log')).read_bytes();rows=[]
for run in manifest['runs']+serial_manifest['runs']:
 label=run['label'];d=load(label);a=run['native_accounting'];blob=log[a['byte_start']:a['byte_end']];forwards=[(int(n),float(t))for n,t in re.findall(rb'\[dsv4\] forward (\d+) tokens in ([\d.]+)s',blob)]
 native={'prefill_calls':sum(n>1 for n,t in forwards),'prefill_tokens':sum(n for n,t in forwards if n>1),'prefill_forward_seconds':sum(t for n,t in forwards if n>1),'decode_calls':sum(n==1 for n,t in forwards),'decode_forward_seconds':sum(t for n,t in forwards if n==1)}
 chats=[(int(n),int(pr),int(reuse),reason.decode())for n,pr,reuse,reason in re.findall(rb'chat.complete tokens=(\d+) promptTokens=(\d+) kvReused=(\d+).*?finishReason=(\S+)',blob)]
 failures=[c for c in d['cases']if c['status']!='ok'];errors=[x.decode(errors='replace')for x in blob.splitlines()if re.search(rb'error|failed|assert|preempt|exception|cancelled',x,re.I)]
 expected={'quality':30,'steady':15,'long':2,'serial-tools':10}[label]
 checks={'run_complete':d['run_complete']is True,'count_matches':len(d['cases'])==d['execution_plan']['expected_cases']==expected,'exit_matches_failures':run['exit_code']==int(bool(failures)),'child_validation_matches':run['child_validation']['failed_cases']==len(failures) and run['child_validation']['run_complete']is True,'child_sha_matches':source(w/(p+'-'+label+'.json'))['sha256']==run['child_validation']['report_sha256'],'range_sha_matches':hashlib.sha256(blob).hexdigest()==a['range_sha256'],'counters_match':all(math.isclose(native[k],v,rel_tol=1e-12,abs_tol=1e-9)for k,v in a.items()if k in native),'prefill_reconciles':native['prefill_tokens']==sum(pr-reuse for n,pr,reuse,reason in chats),'decode_reconciles':native['decode_calls']==sum(n+(reason=='eos')for n,pr,reuse,reason in chats),'warmup_passed':d.get('warmup',{}).get('status')=='ok','no_preemptions':not any('preempt' in x.lower()for x in errors)}
 summaries={}
 for concurrency in sorted(set(c['concurrency']for c in d['cases'])):
  cases=[c for c in d['cases']if c['concurrency']==concurrency];passed=[c for c in cases if c['status']=='ok'];summary={'passed':len(passed),'total':len(cases)}
  if label=='steady':
   summary.update({k+'_median':statistics.median(c['turns'][0]['metrics'][k]for c in passed)for k in ('decode_tps','ttft_ms','total_wall_ms')});summary['all_completions_512']=all(c['turns'][0]['metrics']['completion_tokens']==512 for c in cases);waves=[x for x in d['waves']if x['concurrency']==concurrency];summary['wave_wall_ms_median']=statistics.median(x['wall_ms']for x in waves);summary['aggregate_whole_wave_tps']=concurrency*512/(summary['wave_wall_ms_median']/1000)
  summaries[str(concurrency)]=summary
 rows.append({'label':label,'source':source(w/(p+'-'+label+'.json')),'checks':checks,'all_integrity_checks_passed':all(checks.values()),'passed':len(d['cases'])-len(failures),'total':len(d['cases']),'failures':failures,'summary':summaries,'long_cases':[{'tag':c['tag'],'status':c['status'],'metrics':{k:c['turns'][0]['metrics'][k]for k in ('prompt_tokens','completion_tokens','ttft_ms','total_wall_ms')}}for c in d['cases']]if label=='long'else[],'native':native,'range':{k:a[k]for k in ('byte_start','byte_end','range_sha256')},'chat_complete_count':len(chats),'generated_tokens_with_warmup':sum(n for n,pr,reuse,reason in chats),'eos_count':sum(reason=='eos'for n,pr,reuse,reason in chats),'logged_prompt_tokens':sum(pr for n,pr,reuse,reason in chats),'reused_tokens':sum(reuse for n,pr,reuse,reason in chats),'log_errors':errors})
baseline=load('quality');serial=load('serial-tools');original={c['tag']:c for c in baseline['cases']};policy_pairs=[]
for c in serial['cases']:
 a=original[c['tag']];request=copy.deepcopy(c['turns'][0]['request']);parameter=request['extra_body'].pop('parallel_tool_calls',None);policy_pairs.append({'tag':c['tag'],'prior_status':a['status'],'serial_status':c['status'],'prior_input_sha256':a['input_sha256'],'serial_input_sha256':c['input_sha256'],'only_initial_request_change_is_parallel_false':parameter is False and request==a['turns'][0]['request'],'all_tool_turns_serial':all(t['request']['tools'] and t['request']['extra_body'].get('parallel_tool_calls') is False for t in c['turns']),'input_hash_changed':a['input_sha256']!=c['input_sha256']})
assert len(policy_pairs)==10 and all(x['only_initial_request_change_is_parallel_false'] and x['all_tool_turns_serial'] and x['input_hash_changed'] for x in policy_pairs)
result={'profile':p,'scope':'Historical CPU-MoE4 placement baseline before explicit V4.1 shared-projection device pins. Original quality failure is retained; serial-tools is a separate client-policy follow-up. No isolated placement performance or numerical-fix claim. Qualification remains the root measurement-window declaration.','shared_projection_limitation':'Later same-binary five-layer CUDA fixture observer found old shared gate/up projections placed on CPU in CPU-MoE/TP branches. The exact number of affected full-checkpoint layers was inferred, not directly observed on this historical host. The final pinned candidate is a different native binary.','serial_followup':{'run_complete':serial_manifest['run_complete'],'all_passed':serial_manifest['all_passed'],'metadata':{'serial_tool_workflows':serial['serial_tool_workflows'],'structured_tool_results':serial['structured_tool_results'],'execution_plan':serial['execution_plan'],'harness_sha256':serial['harness_sha256']},'policy_pairs':policy_pairs,'scope':'Explicit parallel_tool_calls=false constrains dependent fixture calls. Preserve the original 29/30 failure; this is not a numerical inference correction or same-request quality comparison.'},'all_integrity_checks_passed':all(r['all_integrity_checks_passed']for r in rows),'original_plan_complete':manifest['run_complete'],'original_plan_all_passed':manifest['all_passed'],'native_sha256':launch['sha256']['libGgmlOps.so'],'managed_runtime_sha256':launch['sha256']['TensorSharp.Runtime.dll'],'launch_command':launch['command'],'launch_environment':launch['environment'],'rows':rows,'sources':[source(path)for path in [pathlib.Path(__file__),w/(p+'-launch.json'),w/(p+'-placement-runs.json'),w/(p+'-serial-tools-runs.json'),w/(p+'-profile-runs.json'),w/(p+'-server.log')]]}
assert result['original_plan_complete']is True and result['original_plan_all_passed']is False
args.output.parent.mkdir(parents=True,exist_ok=True)
args.output.write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps({'all_integrity_checks_passed':result['all_integrity_checks_passed'],'rows':[{k:r[k]for k in ('label','passed','total','summary','long_cases','log_errors')}for r in rows]},indent=2))
raise SystemExit(0 if result['all_integrity_checks_passed']else 1)
