from pathlib import Path
import json
base = Path('/Users/zhongkaifu/work/TensorSharp/docs/validation/deepseek41/final-placements')
r = json.loads((base/'layer8-comparison.json').read_text())
lines = ['# Final layer placement: historical comparisons', '',
'The final layer profile passed its 30 standard quality cases, 15 sustained-decode cases, two single-request long prompts and 10 explicitly serial tool workflows. The independent [manifest](layer8-manifest.json) and [audit](layer8-report.json) verify these 57 cases, their native accounting and the complete outer phase plan. The wrapper records completion of all seven phases; this placement auditor does not automatically credit the other phases. The additional long-parallel audit below verifies all eight of those cases independently.', '',
'The [machine-readable comparison](layer8-comparison.json) retains every planned case, all failures, exact request/output/token-count comparisons and source hashes. Whole scenario/concurrency groups are used; no successful subset is substituted. Ratios describe these recorded configurations and are not an isolated native optimization, managed grammar, or llama.cpp parity result.', '',
'## Controls and configuration differences', '',
'All profiles below use the same Q2_K checkpoint on eight A40 GPUs with native layer placement, CPU-MoE zero, context 65,536, F16 KV and microbatch 1,024.', '',
'| Label | Exact profile | Use and differences |',
'|---|---|---|',
'| Final | `layer8-context65536-ubatch1024-cpumoe0-cputhreads32-sparse1-compact1-chunk1024-6b3-final` | Managed 3651; native `6b3b5ab3`; explicit native CPU threads 32; compact raw gather enabled; fixed four-slot pool; prefill and solo chunk limits both 1,024. |',
'| b26c control | `layer8-context65536-ubatch1024-cpumoe0-sparse1-compact1-slots4-b26c` | Managed 3433; native `b26cac3e`; compact gather and fixed four-slot pool; prefill 256 / solo 8,192. Old CLI 48 was not honored by this native loader; auto 32 is inferred from source, not directly observed on that host. Used for quality and long-parallel. |',
'| 4608 control | `layer8-context65536-ubatch1024-cpumoe0-sparse1-4608` | Earlier managed build and native `4608dd0d`; compact raw gather absent; later scheduler/thread settings not fully recorded. Used only for its complete, predeclared 15-case `decode` scenario within an older 30-case short-plus-decode report. |', '',
'Full binary/environment hashes and launch-source hashes are retained in the comparison JSON. Both controls precede Unicode grammar, tool serialization, reasoning-loop and other managed corrections. Native 6b3 also includes recovery/thread and shared-projection placement corrections. These differences prevent causal attribution to any single change. Historical 4608 reports lack the newer `run_complete`/plan fields; all 15 decode keys and three complete waves at each concurrency were independently reconstructed and matched. The old 30-case wrapper wall time is not compared with the new 15-case wrapper.', '',
'## Sustained decode: complete 15-case group', '',
'Every initial and full request, assistant output, finish reason, prompt count and 512-token completion matches. Each concurrency has three complete repeats. Latency ratios use baseline/final; throughput ratios use final/baseline; values below 1 are slower.', '',
'| Metric | 4608 | Final | Final speed ratio |',
'|---|---:|---:|---:|']
co=r['comparisons']['steady']['groups']
for concurrency in [1,4]:
 g=co[f'decode@c{concurrency}']; a,b=g['baseline'],g['final']; rat=g['speedup_final_over_baseline']
 for label,field,div in [('Per-request decode tokens/s','decode_tps_median',1),('First-token latency (ms)','ttft_ms_median',1),('Whole-wave wall (s)','whole_wave_wall_ms_median',1000),('Whole-wave end-to-end tokens/s','whole_wave_end_to_end_tps_median',1)]:
  lines.append(f'| c{concurrency} {label} | {a[field]/div:.4f} | {b[field]/div:.4f} | {rat[field]:.4f} |')
lines += ['', 'The small decode/whole-wave differences do not establish a systematic speedup. First-token latency is slower by about 1.4% at c1 and 1.5% at c4; these measurements remain in the result.', '',
'## Standard quality: preserve slower latency and changed workflows', '',
'Both b26c and final pass 30/30 semantic cases, and all 30 initial request hashes match. Twenty non-tool cases also match all subsequent requests, complete outputs, finish reasons and token counts. The 10 tool/agentic cases have different follow-up requests, outputs and/or token counts; their timing ratios and a combined 30-case phase ratio are withheld.', '',
'Each table row below uses its entire non-tool scenario/concurrency group: one c1 request or one c4 wave. For multi-turn cases, TTFT means the first turn and wall time means the complete conversation. These are single-repeat observations, not repeated latency estimates.', '',
'| Scenario | Concurrency | TTFT speed ratio | Request/conversation wall speed ratio | Whole-wave wall speed ratio |',
'|---|---:|---:|---:|---:|']
for name,g in r['comparisons']['quality']['groups'].items():
 if 'speedup_final_over_baseline' not in g: continue
 scenario,c=name.split('@'); d=g['speedup_final_over_baseline']
 lines.append(f"| {scenario} | {c} | {d['ttft_ms_median']:.4f} | {d['request_wall_ms_median']:.4f} | {d['whole_wave_wall_ms_median']:.4f} |")
lines += ['',
'The JSON c1 observation is materially slower: TTFT 590.90 → 897.59 ms and whole request 1,053.75 → 1,569.49 ms, with the same 15 generated tokens. Its short-response SSE decode rate is 32.2561 → 21.7860 tokens/s. JSON c4 also has modestly slower TTFT, request wall and short-response decode. Short, schema and multi-turn latency differences above are retained as well. One observation across different builds and scheduler settings cannot establish a cold-grammar cause or a systematic regression.', '',
'The prepared [90-case JSON A/B runner](../scripts/run-final-json-performance.md) will retain the first JSON c1 warmup immediately after a 512-token decode warmup on each fresh immutable host, followed by a JSON c4 warmup. Exact requests, complete outputs, finish reasons and token counts must match before first-use timings are compared. There is only one such first-use observation per model/version, and telemetry begins after warmups: these are diagnostic observations, not qualified timings or isolated grammar-compilation measurements. The 90 measured JSON cases remain a separate repeated comparison. Results from this separate run are not credited by this layer audit.', '',
'## Long prompts and concurrent long prompts', '',
'The final single-request long cases both pass: 7,706 prompt tokens take 21.1848 s including the answer, and 30,585 take 81.4273 s. No preserved earlier CPU0 layer profile has the exact two-case plan: older runs have six cases. Selecting only their first repeat would change the planned workload, so no historical two-case ratio is reported. Likewise, earlier exact 10-case serial-tool controls are CPU-MoE/TP placements, not an earlier CPU0 layer configuration.', '',
'| Complete c4 wave | b26c status | Final status | b26c wall (s) | Final wall (s) | Matched-workload ratio |',
'|---|---:|---:|---:|---:|---:|',
'| 7,706-token prompts | 3/4 | 4/4 | 114.9123 | 86.2952 | Withheld |',
'| 30,585-token prompts | 4/4 | 4/4 | 358.1865 | 326.2040 | 1.0980 |', '',
'The old 8k failure is a Markdown fence around otherwise correct facts: it generated 43 rather than 34 tokens. It remains a failure, and no ratio uses only the three matching successes. All four 32k requests, outputs and token counts match, so its complete-wave ratio is descriptive; all four initial request hashes match at both lengths. The older 4608 long-parallel run has 10 KV-pool preemptions and recomputed prompts and is not used as a clean work-matched comparison.', '',
'For 32k, median TTFT improves from 353.9762 to 321.4451 s, while median **short-answer SSE decode falls from 8.0606 to 7.1289 tokens/s (11.56% lower)**. Both metrics use the same 33 intervals for 34 generated tokens. The old per-request decode windows were 4.0943, 62.0201, 4.0926 and 4.0937 s; one request began emitting 59.5637 s before the other three. Final windows were 4.6289, 4.6289, 4.6292 and 4.7605 s, with first tokens within 0.2633 s. This directly shows different scheduling overlap, consistent with changed prefill/solo chunk policy; it does not erase the measured decline or establish its isolated cause.', '',
'Across both long waves plus warmup, retained native decode accounting is 10.283 s / 291 calls for b26c versus 9.965 s / 282 for final: 35.33677 versus 35.33688 ms per call, effectively equal at the log’s precision. The nine extra old calls equal the nine extra old fenced-response tokens. The complete old server log is unavailable locally, so a 32k-only native execution time cannot be reconstructed independently. The retained old range hash is recorded, without claiming it was freshly recomputed.', '',
'The final long-parallel server-log range was independently rehashed and reconciled: 153 prefill calls, **153,187 prefill tokens** (153,164 measured-request tokens plus 23 warmup), 402.237 s prefill, 282 decode calls / 9.965 s, eight measured answers totaling 272 generated tokens, nine completions including warmup, and zero native errors or preemptions. EOS calls reconcile with completion counts.', '',
'All eight GPUs have sampled SM median 1,740 MHz and memory clock 7,251 MHz in both long-parallel windows; both include lower SM samples (aggregate minimum 1,515 MHz). Matching medians do not prove every in-flight clock or exclude brief contention. [Timing diagnostics](layer8-timing-diagnostics.json) retain each request’s absolute stream times, every per-device clock summary, raw CSV hashes and the native accounting sources.', '',
'## Reproduction and provenance', '',
'The local analysis snapshots are [compare-final-layer.py](../scripts/compare-final-layer.py), [analyze-layer-timing.py](../scripts/analyze-layer-timing.py) and [identify-final-layer-controls.py](../scripts/identify-final-layer-controls.py). They read retained reports only and do not launch inference. Absolute `/tmp` paths identify the original analysis staging layout; the snapshots require that layout or explicit path adaptation to replay. Full source hashes are in [scripts/sources.json](../scripts/sources.json), the report, manifest and timing artifact. The primary raw-report hashes are cross-checked against the corresponding curated full-checkpoint reports before ratios are produced.', '']
(base/'layer8-comparison.md').write_text('\n'.join(lines))
